### ISSUE TITLE
objective function

### ISSUE THREAD

**Issue by fncode246** [JusperLee/Deep-Encoder-Decoder-Conv-TasNet#1]
What is the loss as objective function during training?

**Comment by JusperLee** [comment]
![image](https://user-images.githubusercontent.com/33806018/113510766-e7b18e80-958e-11eb-9056-0610ed41d9e3.png)

**Comment by JusperLee** [comment]
SI-SNR
![image](https://user-images.githubusercontent.com/33806018/113510822-3828ec00-958f-11eb-8c61-65e00bc79587.png)
